/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/magical_abandoned_mine.glb -o src/components/MagicalMine.jsx --keepnames --keepgroups 
Author: WarderiiK (https://sketchfab.com/WarderiiK)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/magical-abandoned-mine-7ae4754b0db74ba884072215b5d013f5
Title: Magical Abandoned Mine
*/

import { Suspense, useEffect } from "react";
import { Canvas } from "@react-three/fiber";
import {
  OrbitControls,
  useAnimations,
  useGLTF,
} from "@react-three/drei";
import { EffectComposer, Bloom } from "@react-three/postprocessing";
import * as THREE from "three";
import { useMediaQuery } from "react-responsive";

const MineModel = ({ onLoaded }) => {

  const { scene, animations } = useGLTF(
  import.meta.env.BASE_URL + "models/magical_abandoned_mine.glb"
);

useEffect(() => {
  console.log("MAGICAL MINE READY");
  onLoaded?.("Magical Mine");
}, [onLoaded]);

const isMobile = useMediaQuery({ maxWidth: 768 });

  // GLB animations
  const { actions } = useAnimations(animations, scene);

  useEffect(() => {
    Object.values(actions).forEach((action) => {
      if (!action) return;

      action.reset();
      action.setLoop(THREE.LoopRepeat, Infinity);
      action.play();
    });

    return () => {
      Object.values(actions).forEach((action) => {
        action?.stop();
      });
    };
  }, [actions]);

  // Crystal + firefly glow
  useEffect(() => {
    scene.traverse((object) => {
      if (!object.isMesh || !object.material) return;

      const objectMaterials = Array.isArray(object.material)
        ? object.material
        : [object.material];

      objectMaterials.forEach((material) => {
        // Crystals
        if (
          object.name.toLowerCase().includes("crystal") ||
          material.name === "Combination"
        ) {
          material.emissive =
            material.emissive || new THREE.Color();

          material.emissive.set("#4da6ff");
          material.emissiveIntensity = 2;
          material.toneMapped = false;
          material.needsUpdate = true;
        }

        // Fireflies
        if (object.name.toLowerCase().includes("firefly")) {
          material.emissive =
            material.emissive || new THREE.Color();

          material.emissive.set("#4da6ff");
          material.emissiveIntensity = 4;
          material.toneMapped = false;
          material.needsUpdate = true;
        }
      });
    });
  }, [scene]);

  return (
    <primitive
      object={scene}
      scale={isMobile ? 0.02 : 0.017}
      position={isMobile ? [5, -4.5, 0] : [3.5, -4, 0]}
      rotation={
        isMobile
          ? [0.1, -1.5, 0.2]
          : [-0.01, -1.45, 0.14]
      }
    />
  );
};

const MagicalMineBackground = ({ onLoaded }) => {
  return (
    <div className="absolute inset-x-0 top-0 h-[calc(97.5%+200px)] w-full overflow-visible -z-10">
      <Canvas
        camera={{
          position: [0, 2, 8],
          fov: 50,
        }}
        dpr={[1, 1.5]}
        gl={{
          antialias: true,
          toneMapping: THREE.ACESFilmicToneMapping,
          toneMappingExposure: 1.2,
        }}
      >
        <color attach="background" args={["#000"]} />

        <fog
          attach="fog"
          args={["#030412", 8, 30]}
        />



        <directionalLight
          position={[5, 8, 5]}
          intensity={1.2}
        />

        {/* Blue / purple environment light */}
        <pointLight
          position={[0, 2, 3]}
          color="#6d7cff"
          intensity={0}
          distance={12}
        />

        <Suspense fallback={null}>
          <MineModel onLoaded={onLoaded} />
        </Suspense>

        {/* Crystal Glow / Bloom */}
        <EffectComposer>
          <Bloom
            intensity={2.2}
            luminanceThreshold={0.15}
            luminanceSmoothing={0.35}
            mipmapBlur
          />
        </EffectComposer>

        <OrbitControls
          enableZoom={false}
          enablePan={false}
          enableRotate={true}
          onChange={(event) => {
            const rotation = event.target.object.rotation;

            console.log(
              "Camera Rotation:",
              "X:",
              rotation.x.toFixed(3),
              "Y:",
              rotation.y.toFixed(3),
              "Z:",
              rotation.z.toFixed(3)
            );
          }}
        />
      </Canvas>
    </div>
  );
};

useGLTF.preload(
  import.meta.env.BASE_URL + "models/magical_abandoned_mine.glb"
);

export default MagicalMineBackground;