/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/magical_abandoned_mine.glb -o src/components/MagicalMine.jsx --keepnames --keepgroups 
Author: WarderiiK (https://sketchfab.com/WarderiiK)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/magical-abandoned-mine-7ae4754b0db74ba884072215b5d013f5
Title: Magical Abandoned Mine
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function MagicalMine(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/magical_abandoned_mine.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e72195cbe977466c9ce75af9cb278eb0fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="FinalScene">
                  <group name="Walls">
                    <group name="polySurface184">
                      <mesh name="polySurface184_RocksMat_0" geometry={nodes.polySurface184_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface185">
                      <mesh name="polySurface185_RocksMat_0" geometry={nodes.polySurface185_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface186">
                      <mesh name="polySurface186_RocksMat_0" geometry={nodes.polySurface186_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface187">
                      <mesh name="polySurface187_RocksMat_0" geometry={nodes.polySurface187_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface188">
                      <mesh name="polySurface188_RocksMat_0" geometry={nodes.polySurface188_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface189">
                      <mesh name="polySurface189_RocksMat_0" geometry={nodes.polySurface189_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface190">
                      <mesh name="polySurface190_RocksMat_0" geometry={nodes.polySurface190_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface191">
                      <mesh name="polySurface191_RocksMat_0" geometry={nodes.polySurface191_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface192">
                      <mesh name="polySurface192_RocksMat_0" geometry={nodes.polySurface192_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface193">
                      <mesh name="polySurface193_RocksMat_0" geometry={nodes.polySurface193_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface194">
                      <mesh name="polySurface194_RocksMat_0" geometry={nodes.polySurface194_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface195">
                      <mesh name="polySurface195_RocksMat_0" geometry={nodes.polySurface195_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface196">
                      <mesh name="polySurface196_RocksMat_0" geometry={nodes.polySurface196_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface197">
                      <mesh name="polySurface197_RocksMat_0" geometry={nodes.polySurface197_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface198">
                      <mesh name="polySurface198_RocksMat_0" geometry={nodes.polySurface198_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface199">
                      <mesh name="polySurface199_RocksMat_0" geometry={nodes.polySurface199_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface200">
                      <mesh name="polySurface200_RocksMat_0" geometry={nodes.polySurface200_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface201">
                      <mesh name="polySurface201_RocksMat_0" geometry={nodes.polySurface201_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface202">
                      <mesh name="polySurface202_RocksMat_0" geometry={nodes.polySurface202_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface203">
                      <mesh name="polySurface203_RocksMat_0" geometry={nodes.polySurface203_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface204">
                      <mesh name="polySurface204_RocksMat_0" geometry={nodes.polySurface204_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface205">
                      <mesh name="polySurface205_RocksMat_0" geometry={nodes.polySurface205_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface206">
                      <mesh name="polySurface206_RocksMat_0" geometry={nodes.polySurface206_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface207">
                      <mesh name="polySurface207_RocksMat_0" geometry={nodes.polySurface207_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface208">
                      <mesh name="polySurface208_RocksMat_0" geometry={nodes.polySurface208_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface209">
                      <mesh name="polySurface209_RocksMat_0" geometry={nodes.polySurface209_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface210">
                      <mesh name="polySurface210_RocksMat_0" geometry={nodes.polySurface210_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface211">
                      <mesh name="polySurface211_RocksMat_0" geometry={nodes.polySurface211_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface212">
                      <mesh name="polySurface212_RocksMat_0" geometry={nodes.polySurface212_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface213">
                      <mesh name="polySurface213_RocksMat_0" geometry={nodes.polySurface213_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface214">
                      <mesh name="polySurface214_RocksMat_0" geometry={nodes.polySurface214_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface215">
                      <mesh name="polySurface215_RocksMat_0" geometry={nodes.polySurface215_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface216">
                      <mesh name="polySurface216_RocksMat_0" geometry={nodes.polySurface216_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface217">
                      <mesh name="polySurface217_RocksMat_0" geometry={nodes.polySurface217_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface218">
                      <mesh name="polySurface218_RocksMat_0" geometry={nodes.polySurface218_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface219">
                      <mesh name="polySurface219_RocksMat_0" geometry={nodes.polySurface219_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface220">
                      <mesh name="polySurface220_RocksMat_0" geometry={nodes.polySurface220_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface221">
                      <mesh name="polySurface221_RocksMat_0" geometry={nodes.polySurface221_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface222">
                      <mesh name="polySurface222_RocksMat_0" geometry={nodes.polySurface222_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface223">
                      <mesh name="polySurface223_RocksMat_0" geometry={nodes.polySurface223_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface224">
                      <mesh name="polySurface224_RocksMat_0" geometry={nodes.polySurface224_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface225">
                      <mesh name="polySurface225_RocksMat_0" geometry={nodes.polySurface225_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface226">
                      <mesh name="polySurface226_RocksMat_0" geometry={nodes.polySurface226_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface227">
                      <mesh name="polySurface227_RocksMat_0" geometry={nodes.polySurface227_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface228">
                      <mesh name="polySurface228_RocksMat_0" geometry={nodes.polySurface228_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface229">
                      <mesh name="polySurface229_RocksMat_0" geometry={nodes.polySurface229_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface230">
                      <mesh name="polySurface230_RocksMat_0" geometry={nodes.polySurface230_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface231">
                      <mesh name="polySurface231_RocksMat_0" geometry={nodes.polySurface231_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface232">
                      <mesh name="polySurface232_RocksMat_0" geometry={nodes.polySurface232_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface233">
                      <mesh name="polySurface233_RocksMat_0" geometry={nodes.polySurface233_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface234">
                      <mesh name="polySurface234_RocksMat_0" geometry={nodes.polySurface234_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface235">
                      <mesh name="polySurface235_RocksMat_0" geometry={nodes.polySurface235_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface236">
                      <mesh name="polySurface236_RocksMat_0" geometry={nodes.polySurface236_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface237">
                      <mesh name="polySurface237_RocksMat_0" geometry={nodes.polySurface237_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface238">
                      <mesh name="polySurface238_RocksMat_0" geometry={nodes.polySurface238_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface239">
                      <mesh name="polySurface239_RocksMat_0" geometry={nodes.polySurface239_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface240">
                      <mesh name="polySurface240_RocksMat_0" geometry={nodes.polySurface240_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface241">
                      <mesh name="polySurface241_RocksMat_0" geometry={nodes.polySurface241_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface242">
                      <mesh name="polySurface242_RocksMat_0" geometry={nodes.polySurface242_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface243">
                      <mesh name="polySurface243_RocksMat_0" geometry={nodes.polySurface243_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface244">
                      <mesh name="polySurface244_RocksMat_0" geometry={nodes.polySurface244_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface245">
                      <mesh name="polySurface245_RocksMat_0" geometry={nodes.polySurface245_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface246">
                      <mesh name="polySurface246_RocksMat_0" geometry={nodes.polySurface246_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface247">
                      <mesh name="polySurface247_RocksMat_0" geometry={nodes.polySurface247_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface248">
                      <mesh name="polySurface248_RocksMat_0" geometry={nodes.polySurface248_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface249">
                      <mesh name="polySurface249_RocksMat_0" geometry={nodes.polySurface249_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface250">
                      <mesh name="polySurface250_RocksMat_0" geometry={nodes.polySurface250_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface251">
                      <mesh name="polySurface251_RocksMat_0" geometry={nodes.polySurface251_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface252">
                      <mesh name="polySurface252_RocksMat_0" geometry={nodes.polySurface252_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface253">
                      <mesh name="polySurface253_RocksMat_0" geometry={nodes.polySurface253_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface254">
                      <mesh name="polySurface254_RocksMat_0" geometry={nodes.polySurface254_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface255" position={[347.061, 66.594, 291.381]} rotation={[-0.508, 0.294, 0.526]} scale={0.223}>
                      <mesh name="polySurface255_RocksMat_0" geometry={nodes.polySurface255_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface256" position={[168.008, 93.031, 196.321]} rotation={[-0.485, -0.038, 0.346]} scale={0.136}>
                      <mesh name="polySurface256_RocksMat_0" geometry={nodes.polySurface256_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface257" position={[-68.207, 124.059, 418.332]} rotation={[1.912, -0.341, -0.642]} scale={0.171}>
                      <mesh name="polySurface257_RocksMat_0" geometry={nodes.polySurface257_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface258" position={[350.597, 65.385, 371.651]} rotation={[-0.644, -0.683, -0.076]} scale={0.223}>
                      <mesh name="polySurface258_RocksMat_0" geometry={nodes.polySurface258_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface259" position={[331.259, 139.77, 306.076]} rotation={[1.166, 0.053, -2.539]} scale={0.166}>
                      <mesh name="polySurface259_RocksMat_0" geometry={nodes.polySurface259_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface260" position={[433.275, 91.13, 204.454]} scale={0.178}>
                      <mesh name="polySurface260_RocksMat_0" geometry={nodes.polySurface260_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface261" position={[-35.053, 37.63, 211.383]} rotation={[0.062, 0.018, 0.155]} scale={0.303}>
                      <mesh name="polySurface261_RocksMat_0" geometry={nodes.polySurface261_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface262" position={[341.351, 75.517, 344.427]} rotation={[2.266, -0.733, 2.517]} scale={0.22}>
                      <mesh name="polySurface262_RocksMat_0" geometry={nodes.polySurface262_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface263" position={[-345.117, 66.561, 287.395]} rotation={[0.727, 1.135, -0.656]} scale={0.21}>
                      <mesh name="polySurface263_RocksMat_0" geometry={nodes.polySurface263_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface264" position={[-225.767, -52.873, 221.108]} rotation={[0.678, 1.041, -0.307]} scale={0.237}>
                      <mesh name="polySurface264_RocksMat_0" geometry={nodes.polySurface264_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface265" position={[-228.771, 17.571, 318.227]} rotation={[1.912, -0.341, -0.642]} scale={0.171}>
                      <mesh name="polySurface265_RocksMat_0" geometry={nodes.polySurface265_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface266" position={[-292.54, 99.744, 424.973]} rotation={[1.51, -0.582, -0.724]} scale={0.216}>
                      <mesh name="polySurface266_RocksMat_0" geometry={nodes.polySurface266_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface267" position={[-188.583, 5.038, 390.013]} rotation={[1.829, -0.118, -0.801]} scale={0.221}>
                      <mesh name="polySurface267_RocksMat_0" geometry={nodes.polySurface267_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface268" position={[-240.237, 68.424, 163.713]} rotation={[1.64, -0.584, -0.879]} scale={0.171}>
                      <mesh name="polySurface268_RocksMat_0" geometry={nodes.polySurface268_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface269" position={[-142.947, -29.525, 122.113]} rotation={[0.678, 1.041, -0.307]} scale={0.21}>
                      <mesh name="polySurface269_RocksMat_0" geometry={nodes.polySurface269_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface270" position={[-134.826, -49.962, 295.622]} rotation={[0.235, 1.074, 0.019]} scale={0.21}>
                      <mesh name="polySurface270_RocksMat_0" geometry={nodes.polySurface270_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface271" position={[-297.258, -33.604, 375.098]} rotation={[0.821, 0.987, -0.709]} scale={0.269}>
                      <mesh name="polySurface271_RocksMat_0" geometry={nodes.polySurface271_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface272" position={[63.064, 325.842, -34]} rotation={[1.505, 0.362, 0.099]} scale={0.41}>
                      <mesh name="polySurface272_RocksMat_0" geometry={nodes.polySurface272_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface273" position={[123.499, -14.415, 227.088]} rotation={[-1.797, 0.727, 0.855]} scale={0.41}>
                      <mesh name="polySurface273_RocksMat_0" geometry={nodes.polySurface273_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface274" position={[14.197, 29.36, -163.949]} scale={0.41}>
                      <mesh name="polySurface274_RocksMat_0" geometry={nodes.polySurface274_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface275" position={[60.835, 9.904, -163.648]} scale={0.41}>
                      <mesh name="polySurface275_RocksMat_0" geometry={nodes.polySurface275_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface276" position={[164.04, -46.714, 77.991]} rotation={[-0.998, -0.742, 0.899]} scale={0.41}>
                      <mesh name="polySurface276_RocksMat_0" geometry={nodes.polySurface276_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface277" position={[414.254, -59.778, -88.976]} rotation={[-0.491, 0.509, 0.126]} scale={0.41}>
                      <mesh name="polySurface277_RocksMat_0" geometry={nodes.polySurface277_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface278" position={[725.823, 25.876, 447.482]} rotation={[-0.293, -0.887, 0.432]} scale={0.41}>
                      <mesh name="polySurface278_RocksMat_0" geometry={nodes.polySurface278_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface279" position={[406.496, 144.495, -171.796]} rotation={[0.641, -0.134, 0.216]} scale={0.41}>
                      <mesh name="polySurface279_RocksMat_0" geometry={nodes.polySurface279_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface280" position={[-16.576, 96.739, 453.032]} rotation={[0.298, 0.067, 1.047]} scale={0.495}>
                      <mesh name="polySurface280_RocksMat_0" geometry={nodes.polySurface280_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface281" position={[107.514, 45.288, 459.714]} rotation={[-0.136, 0, 0]} scale={0.495}>
                      <mesh name="polySurface281_RocksMat_0" geometry={nodes.polySurface281_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface282" position={[-27.213, 6.89, 459.177]} scale={0.495}>
                      <mesh name="polySurface282_RocksMat_0" geometry={nodes.polySurface282_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface283" position={[358.533, 175.364, 351.62]} rotation={[-1.337, 0.174, -2.912]} scale={0.495}>
                      <mesh name="polySurface283_RocksMat_0" geometry={nodes.polySurface283_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface284" position={[362.604, -24.805, 512.933]} rotation={[-0.081, 0.198, 0.266]} scale={0.495}>
                      <mesh name="polySurface284_RocksMat_0" geometry={nodes.polySurface284_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface285" position={[-216.96, 151.155, -235.075]} rotation={[-0.058, 0.66, 0.82]} scale={0.376}>
                      <mesh name="polySurface285_RocksMat_0" geometry={nodes.polySurface285_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface286" position={[-28.251, 75.376, 224.345]} rotation={[0.177, -0.004, 0.401]} scale={0.42}>
                      <mesh name="polySurface286_RocksMat_0" geometry={nodes.polySurface286_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface287" position={[-100.16, -111.074, 383.139]} rotation={[-1.677, -0.912, -3.141]} scale={0.376}>
                      <mesh name="polySurface287_RocksMat_0" geometry={nodes.polySurface287_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface288" position={[-124.233, 90.231, 241.366]} rotation={[0.361, 0.047, 0.124]} scale={0.376}>
                      <mesh name="polySurface288_RocksMat_0" geometry={nodes.polySurface288_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                    <group name="polySurface289" position={[-917.608, -54.322, 480.679]} rotation={[0.075, 1.219, -2.543]}>
                      <mesh name="polySurface289_RocksMat_0" geometry={nodes.polySurface289_RocksMat_0.geometry} material={materials.RocksMat} />
                    </group>
                  </group>
                  <group name="Hero1">
                    <mesh name="Hero1_HeroMat_0" geometry={nodes.Hero1_HeroMat_0.geometry} material={materials.HeroMat} />
                  </group>
                  <group name="Ground1">
                    <mesh name="Ground1_GroundMat_0" geometry={nodes.Ground1_GroundMat_0.geometry} material={materials.GroundMat} />
                  </group>
                  <group name="MineCart1">
                    <mesh name="MineCart1_Combination_0" geometry={nodes.MineCart1_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="MineCart2">
                    <mesh name="MineCart2_Combination_0" geometry={nodes.MineCart2_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="MineTrack1">
                    <mesh name="MineTrack1_Combination_0" geometry={nodes.MineTrack1_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="MineTrack2">
                    <mesh name="MineTrack2_Combination_0" geometry={nodes.MineTrack2_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="MineTrack3">
                    <mesh name="MineTrack3_Combination_0" geometry={nodes.MineTrack3_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="MineTrack4">
                    <mesh name="MineTrack4_Combination_0" geometry={nodes.MineTrack4_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="MineTrack5">
                    <mesh name="MineTrack5_Combination_0" geometry={nodes.MineTrack5_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="MineTrack6">
                    <mesh name="MineTrack6_Combination_0" geometry={nodes.MineTrack6_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Stalegmite10">
                    <mesh name="Stalegmite10_Combination_0" geometry={nodes.Stalegmite10_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Stalegmite11">
                    <mesh name="Stalegmite11_Combination_0" geometry={nodes.Stalegmite11_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Stalegmite12">
                    <mesh name="Stalegmite12_Combination_0" geometry={nodes.Stalegmite12_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Stalegmite13">
                    <mesh name="Stalegmite13_Combination_0" geometry={nodes.Stalegmite13_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Stalegmite14">
                    <mesh name="Stalegmite14_Combination_0" geometry={nodes.Stalegmite14_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Stalegmite15">
                    <mesh name="Stalegmite15_Combination_0" geometry={nodes.Stalegmite15_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Stalegmite16">
                    <mesh name="Stalegmite16_Combination_0" geometry={nodes.Stalegmite16_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Stalegmite17">
                    <mesh name="Stalegmite17_Combination_0" geometry={nodes.Stalegmite17_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Stalegmite18">
                    <mesh name="Stalegmite18_Combination_0" geometry={nodes.Stalegmite18_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Stalegmite19">
                    <mesh name="Stalegmite19_Combination_0" geometry={nodes.Stalegmite19_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Stalegmite20">
                    <mesh name="Stalegmite20_Combination_0" geometry={nodes.Stalegmite20_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Stalegmite21">
                    <mesh name="Stalegmite21_Combination_0" geometry={nodes.Stalegmite21_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Stalegmite22">
                    <mesh name="Stalegmite22_Combination_0" geometry={nodes.Stalegmite22_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Stalegmite23">
                    <mesh name="Stalegmite23_Combination_0" geometry={nodes.Stalegmite23_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Stalegmite24">
                    <mesh name="Stalegmite24_Combination_0" geometry={nodes.Stalegmite24_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Stalegmite25" position={[-156.175, 0, -1.241]}>
                    <mesh name="Stalegmite25_Combination_0" geometry={nodes.Stalegmite25_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Stalegmite26">
                    <mesh name="Stalegmite26_Combination_0" geometry={nodes.Stalegmite26_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Mushrooms4">
                    <mesh name="Mushrooms4_Combination_0" geometry={nodes.Mushrooms4_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Mushrooms7">
                    <mesh name="Mushrooms7_Combination_0" geometry={nodes.Mushrooms7_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Mushrooms8">
                    <mesh name="Mushrooms8_Combination_0" geometry={nodes.Mushrooms8_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Mushrooms9">
                    <mesh name="Mushrooms9_Combination_0" geometry={nodes.Mushrooms9_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Mushrooms10">
                    <mesh name="Mushrooms10_Combination_0" geometry={nodes.Mushrooms10_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Mushrooms11">
                    <mesh name="Mushrooms11_Combination_0" geometry={nodes.Mushrooms11_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Mushrooms12">
                    <mesh name="Mushrooms12_Combination_0" geometry={nodes.Mushrooms12_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Mushrooms13">
                    <mesh name="Mushrooms13_Combination_0" geometry={nodes.Mushrooms13_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Mushrooms14">
                    <mesh name="Mushrooms14_Combination_0" geometry={nodes.Mushrooms14_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Mushrooms21">
                    <mesh name="Mushrooms21_Combination_0" geometry={nodes.Mushrooms21_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Mushrooms22">
                    <mesh name="Mushrooms22_Combination_0" geometry={nodes.Mushrooms22_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal13">
                    <mesh name="Crystal13_Combination_0" geometry={nodes.Crystal13_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal26">
                    <mesh name="Crystal26_Combination_0" geometry={nodes.Crystal26_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal27">
                    <mesh name="Crystal27_Combination_0" geometry={nodes.Crystal27_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal28">
                    <mesh name="Crystal28_Combination_0" geometry={nodes.Crystal28_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal29">
                    <mesh name="Crystal29_Combination_0" geometry={nodes.Crystal29_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal30" position={[-74.271, -5.908, -95.17]} rotation={[0.366, 0.271, -0.352]}>
                    <mesh name="Crystal30_Combination_0" geometry={nodes.Crystal30_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal31">
                    <mesh name="Crystal31_Combination_0" geometry={nodes.Crystal31_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal32">
                    <mesh name="Crystal32_Combination_0" geometry={nodes.Crystal32_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal33">
                    <mesh name="Crystal33_Combination_0" geometry={nodes.Crystal33_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal35">
                    <mesh name="Crystal35_Combination_0" geometry={nodes.Crystal35_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal36" position={[56.485, -33.381, -91.406]} scale={1.197}>
                    <mesh name="Crystal36_Combination_0" geometry={nodes.Crystal36_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal37" position={[-5.887, 26.263, -11.21]} rotation={[0.038, 0.06, 0.112]}>
                    <mesh name="Crystal37_Combination_0" geometry={nodes.Crystal37_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal38" position={[2.364, -4.309, 5.627]}>
                    <mesh name="Crystal38_Combination_0" geometry={nodes.Crystal38_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal39" position={[9.704, -6.187, -4.422]}>
                    <mesh name="Crystal39_Combination_0" geometry={nodes.Crystal39_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal41">
                    <mesh name="Crystal41_Combination_0" geometry={nodes.Crystal41_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal42">
                    <mesh name="Crystal42_Combination_0" geometry={nodes.Crystal42_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal43">
                    <mesh name="Crystal43_Combination_0" geometry={nodes.Crystal43_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal44">
                    <mesh name="Crystal44_Combination_0" geometry={nodes.Crystal44_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal45">
                    <mesh name="Crystal45_Combination_0" geometry={nodes.Crystal45_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal46">
                    <mesh name="Crystal46_Combination_0" geometry={nodes.Crystal46_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal47">
                    <mesh name="Crystal47_Combination_0" geometry={nodes.Crystal47_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal48">
                    <mesh name="Crystal48_Combination_0" geometry={nodes.Crystal48_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal49">
                    <mesh name="Crystal49_Combination_0" geometry={nodes.Crystal49_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal50">
                    <mesh name="Crystal50_Combination_0" geometry={nodes.Crystal50_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal51">
                    <mesh name="Crystal51_Combination_0" geometry={nodes.Crystal51_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal52">
                    <mesh name="Crystal52_Combination_0" geometry={nodes.Crystal52_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal54">
                    <mesh name="Crystal54_Combination_0" geometry={nodes.Crystal54_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal55">
                    <mesh name="Crystal55_Combination_0" geometry={nodes.Crystal55_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal56">
                    <mesh name="Crystal56_Combination_0" geometry={nodes.Crystal56_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal57">
                    <mesh name="Crystal57_Combination_0" geometry={nodes.Crystal57_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal58">
                    <mesh name="Crystal58_Combination_0" geometry={nodes.Crystal58_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal59">
                    <mesh name="Crystal59_Combination_0" geometry={nodes.Crystal59_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal60">
                    <mesh name="Crystal60_Combination_0" geometry={nodes.Crystal60_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal61">
                    <mesh name="Crystal61_Combination_0" geometry={nodes.Crystal61_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal62">
                    <mesh name="Crystal62_Combination_0" geometry={nodes.Crystal62_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal63">
                    <mesh name="Crystal63_Combination_0" geometry={nodes.Crystal63_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal64">
                    <mesh name="Crystal64_Combination_0" geometry={nodes.Crystal64_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal65">
                    <mesh name="Crystal65_Combination_0" geometry={nodes.Crystal65_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal66">
                    <mesh name="Crystal66_Combination_0" geometry={nodes.Crystal66_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal67">
                    <mesh name="Crystal67_Combination_0" geometry={nodes.Crystal67_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal68" position={[121.341, 76.625, 208.857]} rotation={[-0.114, -0.129, -0.021]} scale={0.56}>
                    <mesh name="Crystal68_Combination_0" geometry={nodes.Crystal68_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal69">
                    <mesh name="Crystal69_Combination_0" geometry={nodes.Crystal69_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal70">
                    <mesh name="Crystal70_Combination_0" geometry={nodes.Crystal70_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal71">
                    <mesh name="Crystal71_Combination_0" geometry={nodes.Crystal71_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal72">
                    <mesh name="Crystal72_Combination_0" geometry={nodes.Crystal72_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal73" position={[178.352, 130.675, 141.48]} rotation={[0.017, -0.252, -0.173]} scale={0.56}>
                    <mesh name="Crystal73_Combination_0" geometry={nodes.Crystal73_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal74" position={[125.138, 191.557, 234.816]} rotation={[0.105, -0.122, -0.163]} scale={0.487}>
                    <mesh name="Crystal74_Combination_0" geometry={nodes.Crystal74_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal75" position={[147.618, 113.734, 225.379]} rotation={[-0.043, -0.14, -0.117]} scale={0.487}>
                    <mesh name="Crystal75_Combination_0" geometry={nodes.Crystal75_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal76" position={[182.809, 59.515, 237.54]} rotation={[-0.683, -0.319, -0.675]} scale={0.462}>
                    <mesh name="Crystal76_Combination_0" geometry={nodes.Crystal76_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal77" position={[2.538, 64.747, -14.656]} rotation={[-0.043, -0.14, -0.117]} scale={0.969}>
                    <mesh name="Crystal77_Combination_0" geometry={nodes.Crystal77_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal78" position={[131.587, 174.616, 274.975]} rotation={[-0.149, -0.201, -0.283]} scale={0.417}>
                    <mesh name="Crystal78_Combination_0" geometry={nodes.Crystal78_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal79" position={[91.543, 206.518, 248.15]} rotation={[0.126, -0.011, 0.007]} scale={0.417}>
                    <mesh name="Crystal79_Combination_0" geometry={nodes.Crystal79_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal80" position={[140.466, 243.01, 350.585]} rotation={[-0.108, -0.183, -0.272]} scale={0.258}>
                    <mesh name="Crystal80_Combination_0" geometry={nodes.Crystal80_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal81" position={[139.184, 214.748, 343.477]} rotation={[-0.05, -0.083, -0.068]} scale={0.258}>
                    <mesh name="Crystal81_Combination_0" geometry={nodes.Crystal81_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal82" position={[129.385, 193.569, 325.661]} rotation={[-0.058, -0.034, -0.187]} scale={0.317}>
                    <mesh name="Crystal82_Combination_0" geometry={nodes.Crystal82_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal83" position={[86.93, 52.162, 65.983]} rotation={[0.015, -0.22, -0.168]} scale={0.838}>
                    <mesh name="Crystal83_Combination_0" geometry={nodes.Crystal83_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal84" position={[38.835, 30.46, 73.491]} rotation={[0.006, -0.087, 0.034]} scale={0.838}>
                    <mesh name="Crystal84_Combination_0" geometry={nodes.Crystal84_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal85" position={[87.772, -11.433, 113.023]} rotation={[-0.142, -0.036, 0.258]} scale={0.838}>
                    <mesh name="Crystal85_Combination_0" geometry={nodes.Crystal85_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal86" position={[77.784, 93.338, 135.969]} rotation={[0.079, -0.091, 0.159]} scale={0.69}>
                    <mesh name="Crystal86_Combination_0" geometry={nodes.Crystal86_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal87" position={[57.349, 185.084, 119.299]} rotation={[0.353, -0.045, 0.177]} scale={0.69}>
                    <mesh name="Crystal87_Combination_0" geometry={nodes.Crystal87_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal88" position={[88.889, 26.69, 200.364]} rotation={[-0.186, -0.323, -0.177]} scale={0.683}>
                    <mesh name="Crystal88_Combination_0" geometry={nodes.Crystal88_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal89" position={[-113.086, 62.789, 133.202]} rotation={[-0.008, 0.43, 0.24]} scale={0.773}>
                    <mesh name="Crystal89_Combination_0" geometry={nodes.Crystal89_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal90" position={[2.838, 208.093, 165.982]} rotation={[0.305, 0.037, 0.017]} scale={0.592}>
                    <mesh name="Crystal90_Combination_0" geometry={nodes.Crystal90_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal91" position={[23.566, 13.675, 265.542]} rotation={[-0.331, 0.016, 0.136]} scale={0.592}>
                    <mesh name="Crystal91_Combination_0" geometry={nodes.Crystal91_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal92" position={[-52.251, 24.56, 267.851]} rotation={[-0.373, 0.459, 0.53]} scale={0.592}>
                    <mesh name="Crystal92_Combination_0" geometry={nodes.Crystal92_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal93" position={[-2.357, 17.93, 94.893]} rotation={[-0.071, 0.061, 0.12]} scale={0.83}>
                    <mesh name="Crystal93_Combination_0" geometry={nodes.Crystal93_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal94" position={[-156.049, -64.519, 135.252]} rotation={[-0.356, 0.455, 0.405]} scale={0.83}>
                    <mesh name="Crystal94_Combination_0" geometry={nodes.Crystal94_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal95" position={[-131.147, 57.311, 217.574]} rotation={[-0.129, 0.354, 0.064]} scale={0.574}>
                    <mesh name="Crystal95_Combination_0" geometry={nodes.Crystal95_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal96" position={[-99.085, 11.988, 223.121]} rotation={[-0.222, 0.214, -0.077]} scale={0.574}>
                    <mesh name="Crystal96_Combination_0" geometry={nodes.Crystal96_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal97" position={[-71.522, -2.712, 244.156]} rotation={[-0.281, 0.187, -0.177]} scale={0.574}>
                    <mesh name="Crystal97_Combination_0" geometry={nodes.Crystal97_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal98" position={[-46.437, 68, 258.574]} rotation={[-0.208, -0.128, 0.024]} scale={0.576}>
                    <mesh name="Crystal98_Combination_0" geometry={nodes.Crystal98_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal99" position={[-124.573, 70.022, 217.954]} rotation={[-0.127, -0.006, -0.052]} scale={0.576}>
                    <mesh name="Crystal99_Combination_0" geometry={nodes.Crystal99_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal100" position={[-168.861, 172.706, 256.86]} rotation={[0.01, 0.153, 0.044]} scale={0.452}>
                    <mesh name="Crystal100_Combination_0" geometry={nodes.Crystal100_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal101" position={[-158.288, 84.918, 286.931]} rotation={[-0.199, 0.119, 0.005]} scale={0.452}>
                    <mesh name="Crystal101_Combination_0" geometry={nodes.Crystal101_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal102" position={[-61.39, -44.346, 128.847]} rotation={[-0.078, -0.17, -0.255]} scale={0.805}>
                    <mesh name="Crystal102_Combination_0" geometry={nodes.Crystal102_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal103" position={[-90.595, -3.3, 172.784]} rotation={[0.021, -0.156, -0.246]} scale={0.678}>
                    <mesh name="Crystal103_Combination_0" geometry={nodes.Crystal103_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal104" position={[-154.086, 150.19, 230.011]} rotation={[0.364, -0.124, -0.137]} scale={0.461}>
                    <mesh name="Crystal104_Combination_0" geometry={nodes.Crystal104_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal105" position={[-251.712, 40.056, 256.053]} rotation={[-0.201, 0.398, -0.203]} scale={0.461}>
                    <mesh name="Crystal105_Combination_0" geometry={nodes.Crystal105_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal106" position={[-207.996, 75.696, 228.472]} rotation={[0.062, 0.336, -0.177]} scale={0.461}>
                    <mesh name="Crystal106_Combination_0" geometry={nodes.Crystal106_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal107" position={[-281.224, -60.022, 141.543]} rotation={[-0.245, 0.234, -0.382]} scale={0.634}>
                    <mesh name="Crystal107_Combination_0" geometry={nodes.Crystal107_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal108" position={[-166.695, 56.295, 304.146]} rotation={[-0.228, -0.455, -0.228]} scale={0.523}>
                    <mesh name="Crystal108_Combination_0" geometry={nodes.Crystal108_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal109" position={[-292.931, 70.564, 5.986]} rotation={[-0.076, 0.637, 0.139]} scale={0.666}>
                    <mesh name="Crystal109_Combination_0" geometry={nodes.Crystal109_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal110" position={[-312.423, 11.817, 175.229]} rotation={[0.019, -0.087, -0.702]} scale={0.482}>
                    <mesh name="Crystal110_Combination_0" geometry={nodes.Crystal110_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal111" position={[-165.19, 84.224, 170.668]} rotation={[0.074, -0.276, -0.131]} scale={0.591}>
                    <mesh name="Crystal111_Combination_0" geometry={nodes.Crystal111_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal112" position={[-214.738, 102.599, 96.681]} rotation={[0.186, -0.134, -0.204]} scale={0.553}>
                    <mesh name="Crystal112_Combination_0" geometry={nodes.Crystal112_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal113" position={[-117.862, 92.027, 169.016]} rotation={[0.168, -0.315, -0.077]} scale={0.643}>
                    <mesh name="Crystal113_Combination_0" geometry={nodes.Crystal113_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal114" position={[-187.815, -48.408, 129.177]} rotation={[-0.056, -0.193, -0.392]} scale={0.725}>
                    <mesh name="Crystal114_Combination_0" geometry={nodes.Crystal114_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal115" position={[-122.113, 171.184, 134.517]} rotation={[0.211, -0.198, 0.085]} scale={0.628}>
                    <mesh name="Crystal115_Combination_0" geometry={nodes.Crystal115_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal116" position={[-78.84, 14.647, -15.632]} rotation={[0.124, -0.046, -0.126]} scale={0.914}>
                    <mesh name="Crystal116_Combination_0" geometry={nodes.Crystal116_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal117" position={[-149.887, 68.764, 6.664]} rotation={[0.256, -0.261, -0.118]} scale={0.611}>
                    <mesh name="Crystal117_Combination_0" geometry={nodes.Crystal117_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal118" position={[-125.509, -10.962, -26.745]} rotation={[0.096, 0.009, -0.252]} scale={0.801}>
                    <mesh name="Crystal118_Combination_0" geometry={nodes.Crystal118_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal119" position={[-187.311, 55.977, -32.511]} rotation={[0.312, -0.184, -0.297]} scale={0.653}>
                    <mesh name="Crystal119_Combination_0" geometry={nodes.Crystal119_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal120" position={[-79.573, 40.533, -40.285]} rotation={[0.468, -0.183, -0.065]} scale={0.826}>
                    <mesh name="Crystal120_Combination_0" geometry={nodes.Crystal120_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal121" position={[-84.202, 48.18, -26.84]} rotation={[0.148, 0.086, -0.153]} scale={0.698}>
                    <mesh name="Crystal121_Combination_0" geometry={nodes.Crystal121_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal122" position={[-117.399, 55.012, -30.21]} rotation={[0.313, -0.029, -0.186]} scale={0.651}>
                    <mesh name="Crystal122_Combination_0" geometry={nodes.Crystal122_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal123" position={[-139.678, 56.12, -71.631]} rotation={[0.277, 0.227, -0.431]} scale={0.651}>
                    <mesh name="Crystal123_Combination_0" geometry={nodes.Crystal123_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal124" position={[-90.63, 92.538, -7.038]} rotation={[0.178, -0.084, 0.014]} scale={0.651}>
                    <mesh name="Crystal124_Combination_0" geometry={nodes.Crystal124_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal125" position={[-79.211, 51.118, -22.027]} rotation={[0.173, 0.039, -0.092]} scale={0.651}>
                    <mesh name="Crystal125_Combination_0" geometry={nodes.Crystal125_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal126" position={[-4.171, 12.619, -48.12]} rotation={[0.258, 0.057, -0.16]} scale={0.896}>
                    <mesh name="Crystal126_Combination_0" geometry={nodes.Crystal126_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal127" position={[-76.577, 50.466, -131.494]} rotation={[0.5, 0.152, -0.332]} scale={0.896}>
                    <mesh name="Crystal127_Combination_0" geometry={nodes.Crystal127_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal128" position={[-32.879, 134.069, -77.882]} rotation={[0.511, 0.193, -0.289]} scale={0.586}>
                    <mesh name="Crystal128_Combination_0" geometry={nodes.Crystal128_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal129" position={[-73.375, 109.044, -24.6]} rotation={[0.207, 0.345, -0.395]} scale={0.586}>
                    <mesh name="Crystal129_Combination_0" geometry={nodes.Crystal129_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal130" position={[-106.701, 112.628, -54.798]} rotation={[0.382, 0.308, -0.401]} scale={0.586}>
                    <mesh name="Crystal130_Combination_0" geometry={nodes.Crystal130_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal131" position={[-33.23, 113.039, -57.794]} rotation={[0.414, 0.08, -0.071]} scale={0.586}>
                    <mesh name="Crystal131_Combination_0" geometry={nodes.Crystal131_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal132" position={[54.482, 46.926, -8.834]} rotation={[0.041, -0.25, 0.181]} scale={0.744}>
                    <mesh name="Crystal132_Combination_0" geometry={nodes.Crystal132_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal133" position={[66.938, 107.863, -27.798]} rotation={[0.239, -0.085, 0.002]} scale={0.637}>
                    <mesh name="Crystal133_Combination_0" geometry={nodes.Crystal133_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal134" position={[59.423, 87.298, -31.378]} rotation={[0.262, -0.134, 0.038]} scale={0.637}>
                    <mesh name="Crystal134_Combination_0" geometry={nodes.Crystal134_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal135" position={[45.151, 31.347, 42.124]} rotation={[-0.173, 0.023, 0.073]} scale={0.785}>
                    <mesh name="Crystal135_Combination_0" geometry={nodes.Crystal135_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal136" position={[86.099, 126.387, 63.3]} rotation={[0.053, 0.297, -0.225]} scale={0.538}>
                    <mesh name="Crystal136_Combination_0" geometry={nodes.Crystal136_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal137" position={[77.617, 129.988, 47.491]} rotation={[0.181, 0.209, -0.313]} scale={0.538}>
                    <mesh name="Crystal137_Combination_0" geometry={nodes.Crystal137_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal138" position={[123.707, 96.937, -40.413]} rotation={[0.423, -0.25, 0.185]} scale={0.538}>
                    <mesh name="Crystal138_Combination_0" geometry={nodes.Crystal138_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal139" position={[54.987, 123.572, 29.437]} rotation={[0.273, 0.122, -0.319]} scale={0.586}>
                    <mesh name="Crystal139_Combination_0" geometry={nodes.Crystal139_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal140" position={[139.02, 75.578, -49.993]} rotation={[0.319, -0.392, 0.316]} scale={0.586}>
                    <mesh name="Crystal140_Combination_0" geometry={nodes.Crystal140_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal141" position={[-247.836, 29.94, 220.184]} rotation={[-0.056, -0.208, -0.475]} scale={0.482}>
                    <mesh name="Crystal141_Combination_0" geometry={nodes.Crystal141_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal142" position={[-390.055, 172.554, 57.069]} rotation={[0.569, 0.488, -0.543]} scale={0.482}>
                    <mesh name="Crystal142_Combination_0" geometry={nodes.Crystal142_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal143" position={[-318.461, 198.973, 76.565]} rotation={[0.512, 0.356, -0.281]} scale={0.482}>
                    <mesh name="Crystal143_Combination_0" geometry={nodes.Crystal143_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal144" position={[111.488, 100.419, 98.359]} rotation={[0.039, 0.324, -0.154]} scale={0.691}>
                    <mesh name="Crystal144_Combination_0" geometry={nodes.Crystal144_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal145" position={[204.383, 122.385, -138.585]} rotation={[0.643, -0.422, 0.288]} scale={0.574}>
                    <mesh name="Crystal145_Combination_0" geometry={nodes.Crystal145_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal146" position={[-12.943, 83.302, 22.814]} rotation={[0.506, 0.252, -0.166]} scale={0.883}>
                    <mesh name="Crystal146_Combination_0" geometry={nodes.Crystal146_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Crystal147" position={[195.846, 94.472, -94.012]} rotation={[0.457, -0.301, 0.163]} scale={0.574}>
                    <mesh name="Crystal147_Combination_0" geometry={nodes.Crystal147_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Torch1" position={[572.44, 60.686, 881.179]} rotation={[-Math.PI, -0.106, -Math.PI]}>
                    <mesh name="Torch1_Combination_0" geometry={nodes.Torch1_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Torch2" position={[178.233, 27.016, 934.945]} rotation={[-Math.PI, 0.134, -Math.PI]}>
                    <mesh name="Torch2_Combination_0" geometry={nodes.Torch2_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="Torch3" position={[69.807, 49.181, -374.738]} rotation={[0, -0.004, 0]}>
                    <mesh name="Torch3_Combination_0" geometry={nodes.Torch3_Combination_0.geometry} material={materials.Combination} />
                  </group>
                  <group name="BLOCK" position={[0, 383.062, -133.323]} rotation={[0.458, -0.073, -0.18]} scale={[1146.465, 1146.465, 213.112]}>
                    <mesh name="BLOCK_lambert1_0" geometry={nodes.BLOCK_lambert1_0.geometry} material={materials.lambert1} />
                  </group>
                  <group name="Animating">
                    <group name="Water3" position={[-138.969, 105.693, 230.379]}>
                      <mesh name="Water3_WaterMat_0" geometry={nodes.Water3_WaterMat_0.geometry} material={materials.WaterMat} />
                    </group>
                    <group name="Cart">
                      <group name="Firefly26" position={[211.443, 227.111, 341.192]}>
                        <mesh name="Firefly26_Combination_0" geometry={nodes.Firefly26_Combination_0.geometry} material={materials.Combination} />
                      </group>
                      <group name="Firefly25" position={[185.921, 240.901, 312.196]}>
                        <mesh name="Firefly25_Combination_0" geometry={nodes.Firefly25_Combination_0.geometry} material={materials.Combination} />
                      </group>
                      <group name="Firefly24" position={[179.259, 207.737, 276.585]}>
                        <mesh name="Firefly24_Combination_0" geometry={nodes.Firefly24_Combination_0.geometry} material={materials.Combination} />
                      </group>
                      <group name="Firefly23" position={[261.516, 205.199, 373.878]}>
                        <mesh name="Firefly23_Combination_0" geometry={nodes.Firefly23_Combination_0.geometry} material={materials.Combination} />
                      </group>
                      <group name="Firefly22" position={[235.07, 256.299, 377.51]}>
                        <mesh name="Firefly22_Combination_0" geometry={nodes.Firefly22_Combination_0.geometry} material={materials.Combination} />
                      </group>
                      <group name="Firefly21" position={[280.501, 237.773, 311.057]}>
                        <mesh name="Firefly21_Combination_0" geometry={nodes.Firefly21_Combination_0.geometry} material={materials.Combination} />
                      </group>
                      <group name="Firefly20" position={[192.894, 228.861, 351.19]}>
                        <mesh name="Firefly20_Combination_0" geometry={nodes.Firefly20_Combination_0.geometry} material={materials.Combination} />
                      </group>
                      <group name="Firefly19" position={[216.914, 230.313, 291.861]}>
                        <mesh name="Firefly19_Combination_0" geometry={nodes.Firefly19_Combination_0.geometry} material={materials.Combination} />
                      </group>
                      <group name="Firefly18" position={[251.202, 255.922, 338.689]}>
                        <mesh name="Firefly18_Combination_0" geometry={nodes.Firefly18_Combination_0.geometry} material={materials.Combination} />
                      </group>
                      <group name="Firefly17" position={[162.141, 224.375, 312.376]}>
                        <mesh name="Firefly17_Combination_0" geometry={nodes.Firefly17_Combination_0.geometry} material={materials.Combination} />
                      </group>
                    </group>
                    <group name="Crystal">
                      <group name="Firefly13" position={[-260.484, 193.785, 94.378]}>
                        <mesh name="Firefly13_Combination_0" geometry={nodes.Firefly13_Combination_0.geometry} material={materials.Combination} />
                      </group>
                      <group name="Firefly14" position={[-317.718, 335.526, 218.565]}>
                        <mesh name="Firefly14_Combination_0" geometry={nodes.Firefly14_Combination_0.geometry} material={materials.Combination} />
                      </group>
                      <group name="Firefly15" position={[-274.743, 366.709, 107.832]}>
                        <mesh name="Firefly15_Combination_0" geometry={nodes.Firefly15_Combination_0.geometry} material={materials.Combination} />
                      </group>
                      <group name="Firefly16" position={[-297.137, 329.329, 45.605]}>
                        <mesh name="Firefly16_Combination_0" geometry={nodes.Firefly16_Combination_0.geometry} material={materials.Combination} />
                      </group>
                      <group name="Firefly12" position={[-281.406, 286.549, 48.864]}>
                        <mesh name="Firefly12_Combination_0" geometry={nodes.Firefly12_Combination_0.geometry} material={materials.Combination} />
                      </group>
                      <group name="Firefly11" position={[-283.368, 291.202, 131.368]}>
                        <mesh name="Firefly11_Combination_0" geometry={nodes.Firefly11_Combination_0.geometry} material={materials.Combination} />
                      </group>
                      <group name="Firefly10" position={[-329.534, 295.583, 196.184]}>
                        <mesh name="Firefly10_Combination_0" geometry={nodes.Firefly10_Combination_0.geometry} material={materials.Combination} />
                      </group>
                      <group name="Firefly9" position={[-414.786, 281.861, 218.081]}>
                        <mesh name="Firefly9_Combination_0" geometry={nodes.Firefly9_Combination_0.geometry} material={materials.Combination} />
                      </group>
                      <group name="Firefly8" position={[-303.969, 241.27, 161.775]}>
                        <mesh name="Firefly8_Combination_0" geometry={nodes.Firefly8_Combination_0.geometry} material={materials.Combination} />
                      </group>
                      <group name="Firefly7" position={[-286.886, 172.694, 204.724]}>
                        <mesh name="Firefly7_Combination_0" geometry={nodes.Firefly7_Combination_0.geometry} material={materials.Combination} />
                      </group>
                      <group name="Firefly6" position={[-330.079, 209.196, 276.449]}>
                        <mesh name="Firefly6_Combination_0" geometry={nodes.Firefly6_Combination_0.geometry} material={materials.Combination} />
                      </group>
                      <group name="Firefly5" position={[-319.093, 262.863, 216.818]}>
                        <mesh name="Firefly5_Combination_0" geometry={nodes.Firefly5_Combination_0.geometry} material={materials.Combination} />
                      </group>
                      <group name="Firefly3" position={[-254.557, 232.962, 150.933]}>
                        <mesh name="Firefly3_Combination_0" geometry={nodes.Firefly3_Combination_0.geometry} material={materials.Combination} />
                      </group>
                      <group name="Firefly2" position={[-251.728, 256.398, 77.003]}>
                        <mesh name="Firefly2_Combination_0" geometry={nodes.Firefly2_Combination_0.geometry} material={materials.Combination} />
                      </group>
                    </group>
                  </group>
                  <group name="Fish">
                    <group name="Object_596">
                      <primitive object={nodes._rootJoint} />
                      <group name="Object_598" position={[218.431, 9.775, 311.255]} rotation={[0, -1.128, -0.002]} />
                      <group name="Object_600" position={[-250.739, 0, -76.603]} rotation={[0, 0.666, 0]} />
                      <group name="Object_602" position={[52.129, 0, 19.946]} rotation={[0, -0.335, 0]} />
                      <group name="Object_604" position={[23.429, 1.566, 92.7]} rotation={[0.009, -0.325, 0.014]} />
                      <group name="Object_606" position={[-264.939, 7.689, 61.655]} rotation={[3.123, 0.838, -3.081]} />
                      <group name="Object_608" position={[-200.306, -0.104, -31.143]} rotation={[0, 1.569, 0]} />
                      <group name="Object_610" position={[-206.825, 0, -66.489]} rotation={[0, 0.577, 0]} />
                      <group name="Object_612" position={[-514.454, -0.11, 107.974]} rotation={[-Math.PI, 1.46, -Math.PI]} />
                      <group name="FishBig_01" position={[218.431, 9.775, 311.255]} rotation={[0, -1.128, -0.002]} />
                      <group name="FishBig_02" position={[-250.739, 0, -76.603]} rotation={[0, 0.666, 0]} />
                      <group name="FishBig_03" position={[52.129, 0, 19.946]} rotation={[0, -0.335, 0]} />
                      <group name="FishLong_01" position={[23.429, 1.566, 92.7]} rotation={[0.009, -0.325, 0.014]} />
                      <group name="FishLong_02" position={[-264.939, 7.689, 61.655]} rotation={[3.123, 0.838, -3.081]} />
                      <group name="FishLong_03" position={[-200.306, -0.104, -31.143]} rotation={[0, 1.569, 0]} />
                      <group name="FishLong_04" position={[-206.825, 0, -66.489]} rotation={[0, 0.577, 0]} />
                      <group name="FishLong_05" position={[-514.454, -0.11, 107.974]} rotation={[-Math.PI, 1.46, -Math.PI]} />
                      <skinnedMesh name="Object_599" geometry={nodes.Object_599.geometry} material={materials.Combination} skeleton={nodes.Object_599.skeleton} />
                      <skinnedMesh name="Object_601" geometry={nodes.Object_601.geometry} material={materials.Combination} skeleton={nodes.Object_601.skeleton} />
                      <skinnedMesh name="Object_603" geometry={nodes.Object_603.geometry} material={materials.Combination} skeleton={nodes.Object_603.skeleton} />
                      <skinnedMesh name="Object_605" geometry={nodes.Object_605.geometry} material={materials.Combination} skeleton={nodes.Object_605.skeleton} />
                      <skinnedMesh name="Object_607" geometry={nodes.Object_607.geometry} material={materials.Combination} skeleton={nodes.Object_607.skeleton} />
                      <skinnedMesh name="Object_609" geometry={nodes.Object_609.geometry} material={materials.Combination} skeleton={nodes.Object_609.skeleton} />
                      <skinnedMesh name="Object_611" geometry={nodes.Object_611.geometry} material={materials.Combination} skeleton={nodes.Object_611.skeleton} />
                      <skinnedMesh name="Object_613" geometry={nodes.Object_613.geometry} material={materials.Combination} skeleton={nodes.Object_613.skeleton} />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/magical_abandoned_mine.glb')
